# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Wed Jun 26 17:36:28 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(771, 572)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.rosButton = QtGui.QPushButton(self.centralWidget)
        self.rosButton.setGeometry(QtCore.QRect(30, 20, 201, 91))
        self.rosButton.setCheckable(True)
        self.rosButton.setObjectName("rosButton")
        self.rcButton = QtGui.QPushButton(self.centralWidget)
        self.rcButton.setGeometry(QtCore.QRect(240, 20, 181, 71))
        self.rcButton.setCheckable(True)
        self.rcButton.setObjectName("rcButton")
        self.attackButton = QtGui.QPushButton(self.centralWidget)
        self.attackButton.setGeometry(QtCore.QRect(240, 90, 181, 71))
        self.attackButton.setCheckable(True)
        self.attackButton.setObjectName("attackButton")
        self.actualSpeedLCD = QtGui.QLCDNumber(self.centralWidget)
        self.actualSpeedLCD.setGeometry(QtCore.QRect(40, 220, 171, 71))
        self.actualSpeedLCD.setObjectName("actualSpeedLCD")
        self.expectedLabel = QtGui.QLabel(self.centralWidget)
        self.expectedLabel.setGeometry(QtCore.QRect(250, 170, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.expectedLabel.setFont(font)
        self.expectedLabel.setStyleSheet("background-color: green; color: white;")
        self.expectedLabel.setObjectName("expectedLabel")
        self.actualLabel = QtGui.QLabel(self.centralWidget)
        self.actualLabel.setGeometry(QtCore.QRect(250, 230, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.actualLabel.setFont(font)
        self.actualLabel.setStyleSheet("background-color: green; color: white;")
        self.actualLabel.setObjectName("actualLabel")
        self.desiredSpeedLabel = QtGui.QLabel(self.centralWidget)
        self.desiredSpeedLabel.setGeometry(QtCore.QRect(70, 120, 101, 16))
        self.desiredSpeedLabel.setObjectName("desiredSpeedLabel")
        self.desiredSpeedEdit = QtGui.QLineEdit(self.centralWidget)
        self.desiredSpeedEdit.setGeometry(QtCore.QRect(60, 150, 113, 21))
        self.desiredSpeedEdit.setObjectName("desiredSpeedEdit")
        self.actualSpeedLabel = QtGui.QLabel(self.centralWidget)
        self.actualSpeedLabel.setGeometry(QtCore.QRect(80, 200, 121, 16))
        self.actualSpeedLabel.setObjectName("actualSpeedLabel")
        self.console = QtGui.QPlainTextEdit(self.centralWidget)
        self.console.setGeometry(QtCore.QRect(40, 310, 711, 191))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(13)
        self.console.setFont(font)
        self.console.setPlainText("")
        self.console.setObjectName("console")
        self.graphicsView = QtGui.QGraphicsView(self.centralWidget)
        self.graphicsView.setGeometry(QtCore.QRect(440, 20, 311, 271))
        self.graphicsView.setObjectName("graphicsView")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar()
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 771, 22))
        self.menuBar.setNativeMenuBar(False)
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setMenuRole(QtGui.QAction.QuitRole)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setMenuRole(QtGui.QAction.AboutRole)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "HACMS Demo", None, QtGui.QApplication.UnicodeUTF8))
        self.rosButton.setText(QtGui.QApplication.translate("MainWindow", "ROS", None, QtGui.QApplication.UnicodeUTF8))
        self.rcButton.setText(QtGui.QApplication.translate("MainWindow", "Resilient Controller", None, QtGui.QApplication.UnicodeUTF8))
        self.attackButton.setText(QtGui.QApplication.translate("MainWindow", "Attack", None, QtGui.QApplication.UnicodeUTF8))
        self.expectedLabel.setText(QtGui.QApplication.translate("MainWindow", "Expected", None, QtGui.QApplication.UnicodeUTF8))
        self.actualLabel.setText(QtGui.QApplication.translate("MainWindow", "Actual", None, QtGui.QApplication.UnicodeUTF8))
        self.desiredSpeedLabel.setText(QtGui.QApplication.translate("MainWindow", "Desired Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.desiredSpeedEdit.setText(QtGui.QApplication.translate("MainWindow", "3.0", None, QtGui.QApplication.UnicodeUTF8))
        self.actualSpeedLabel.setText(QtGui.QApplication.translate("MainWindow", "Actual Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

