# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/demo.ui'
#
# Created: Mon Jul 15 17:16:10 2013
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1249, 708)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.landsharkButton = QtGui.QPushButton(self.centralWidget)
        self.landsharkButton.setGeometry(QtCore.QRect(20, 10, 241, 101))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.landsharkButton.setFont(font)
        self.landsharkButton.setStyleSheet(_fromUtf8("QPushButton:checked {background: rgba(60, 179, 113, 255);}"))
        self.landsharkButton.setCheckable(True)
        self.landsharkButton.setObjectName(_fromUtf8("landsharkButton"))
        self.rcButton = QtGui.QPushButton(self.centralWidget)
        self.rcButton.setEnabled(False)
        self.rcButton.setGeometry(QtCore.QRect(20, 230, 241, 101))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.rcButton.setFont(font)
        self.rcButton.setStyleSheet(_fromUtf8("QPushButton:checked {background: rgba(60, 179, 113, 255);}"))
        self.rcButton.setCheckable(True)
        self.rcButton.setObjectName(_fromUtf8("rcButton"))
        self.attackButton = QtGui.QPushButton(self.centralWidget)
        self.attackButton.setEnabled(False)
        self.attackButton.setGeometry(QtCore.QRect(20, 340, 241, 101))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.attackButton.setFont(font)
        self.attackButton.setStyleSheet(_fromUtf8("QPushButton:checked {background: red;}"))
        self.attackButton.setCheckable(True)
        self.attackButton.setObjectName(_fromUtf8("attackButton"))
        self.actualSpeedLCD = QtGui.QLCDNumber(self.centralWidget)
        self.actualSpeedLCD.setEnabled(False)
        self.actualSpeedLCD.setGeometry(QtCore.QRect(280, 300, 171, 71))
        self.actualSpeedLCD.setObjectName(_fromUtf8("actualSpeedLCD"))
        self.estimatedLabel = QtGui.QLabel(self.centralWidget)
        self.estimatedLabel.setEnabled(False)
        self.estimatedLabel.setGeometry(QtCore.QRect(1470, 270, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.estimatedLabel.setFont(font)
        self.estimatedLabel.setStyleSheet(_fromUtf8("background-color: green; color: white;"))
        self.estimatedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.estimatedLabel.setObjectName(_fromUtf8("estimatedLabel"))
        self.actualLabel = QtGui.QLabel(self.centralWidget)
        self.actualLabel.setEnabled(False)
        self.actualLabel.setGeometry(QtCore.QRect(1470, 230, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actualLabel.setFont(font)
        self.actualLabel.setStyleSheet(_fromUtf8("background-color: green; color: white;"))
        self.actualLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.actualLabel.setObjectName(_fromUtf8("actualLabel"))
        self.desiredSpeedLabel = QtGui.QLabel(self.centralWidget)
        self.desiredSpeedLabel.setEnabled(False)
        self.desiredSpeedLabel.setGeometry(QtCore.QRect(280, 19, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.desiredSpeedLabel.setFont(font)
        self.desiredSpeedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.desiredSpeedLabel.setObjectName(_fromUtf8("desiredSpeedLabel"))
        self.desiredSpeedEdit = QtGui.QLineEdit(self.centralWidget)
        self.desiredSpeedEdit.setEnabled(False)
        self.desiredSpeedEdit.setGeometry(QtCore.QRect(280, 50, 91, 39))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.desiredSpeedEdit.setFont(font)
        self.desiredSpeedEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.desiredSpeedEdit.setObjectName(_fromUtf8("desiredSpeedEdit"))
        self.actualSpeedLabel = QtGui.QLabel(self.centralWidget)
        self.actualSpeedLabel.setEnabled(False)
        self.actualSpeedLabel.setGeometry(QtCore.QRect(280, 280, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.actualSpeedLabel.setFont(font)
        self.actualSpeedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.actualSpeedLabel.setObjectName(_fromUtf8("actualSpeedLabel"))
        self.console = QtGui.QPlainTextEdit(self.centralWidget)
        self.console.setGeometry(QtCore.QRect(20, 490, 1211, 161))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(13)
        self.console.setFont(font)
        self.console.setPlainText(_fromUtf8(""))
        self.console.setObjectName(_fromUtf8("console"))
        self.outputPlot = QtGui.QWidget(self.centralWidget)
        self.outputPlot.setEnabled(False)
        self.outputPlot.setGeometry(QtCore.QRect(470, 280, 331, 201))
        self.outputPlot.setStyleSheet(_fromUtf8("background-color: white;"))
        self.outputPlot.setObjectName(_fromUtf8("outputPlot"))
        self.outputPlotLabel = QtGui.QLabel(self.centralWidget)
        self.outputPlotLabel.setEnabled(False)
        self.outputPlotLabel.setGeometry(QtCore.QRect(470, 250, 51, 16))
        self.outputPlotLabel.setObjectName(_fromUtf8("outputPlotLabel"))
        self.estimatedSpeedLabel = QtGui.QLabel(self.centralWidget)
        self.estimatedSpeedLabel.setEnabled(False)
        self.estimatedSpeedLabel.setGeometry(QtCore.QRect(280, 390, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.estimatedSpeedLabel.setFont(font)
        self.estimatedSpeedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.estimatedSpeedLabel.setObjectName(_fromUtf8("estimatedSpeedLabel"))
        self.estimatedSpeedLCD = QtGui.QLCDNumber(self.centralWidget)
        self.estimatedSpeedLCD.setEnabled(False)
        self.estimatedSpeedLCD.setGeometry(QtCore.QRect(280, 410, 171, 71))
        self.estimatedSpeedLCD.setObjectName(_fromUtf8("estimatedSpeedLCD"))
        self.ccButton = QtGui.QPushButton(self.centralWidget)
        self.ccButton.setEnabled(False)
        self.ccButton.setGeometry(QtCore.QRect(20, 120, 241, 101))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.ccButton.setFont(font)
        self.ccButton.setStyleSheet(_fromUtf8("QPushButton:checked {background: rgba(60, 179, 113, 255);}"))
        self.ccButton.setCheckable(True)
        self.ccButton.setObjectName(_fromUtf8("ccButton"))
        self.setSpeedButton = QtGui.QPushButton(self.centralWidget)
        self.setSpeedButton.setEnabled(False)
        self.setSpeedButton.setGeometry(QtCore.QRect(380, 50, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.setSpeedButton.setFont(font)
        self.setSpeedButton.setObjectName(_fromUtf8("setSpeedButton"))
        self.inputPlotLabel = QtGui.QLabel(self.centralWidget)
        self.inputPlotLabel.setEnabled(False)
        self.inputPlotLabel.setGeometry(QtCore.QRect(470, 10, 41, 16))
        self.inputPlotLabel.setObjectName(_fromUtf8("inputPlotLabel"))
        self.inputPlot = QtGui.QWidget(self.centralWidget)
        self.inputPlot.setEnabled(False)
        self.inputPlot.setGeometry(QtCore.QRect(470, 40, 331, 201))
        self.inputPlot.setStyleSheet(_fromUtf8("background-color: white;"))
        self.inputPlot.setObjectName(_fromUtf8("inputPlot"))
        self.rightPlot = QtGui.QWidget(self.centralWidget)
        self.rightPlot.setEnabled(False)
        self.rightPlot.setGeometry(QtCore.QRect(810, 40, 421, 441))
        self.rightPlot.setStyleSheet(_fromUtf8("background-color: white;"))
        self.rightPlot.setObjectName(_fromUtf8("rightPlot"))
        self.rightPlotLabel = QtGui.QLabel(self.centralWidget)
        self.rightPlotLabel.setEnabled(False)
        self.rightPlotLabel.setGeometry(QtCore.QRect(810, 10, 71, 16))
        self.rightPlotLabel.setObjectName(_fromUtf8("rightPlotLabel"))
        self.attack1RadioButton = QtGui.QRadioButton(self.centralWidget)
        self.attack1RadioButton.setEnabled(False)
        self.attack1RadioButton.setGeometry(QtCore.QRect(1330, 230, 121, 20))
        self.attack1RadioButton.setChecked(True)
        self.attack1RadioButton.setObjectName(_fromUtf8("attack1RadioButton"))
        self.attack2RadioButton = QtGui.QRadioButton(self.centralWidget)
        self.attack2RadioButton.setEnabled(False)
        self.attack2RadioButton.setGeometry(QtCore.QRect(1330, 260, 121, 20))
        self.attack2RadioButton.setObjectName(_fromUtf8("attack2RadioButton"))
        self.attack3RadioButton = QtGui.QRadioButton(self.centralWidget)
        self.attack3RadioButton.setEnabled(False)
        self.attack3RadioButton.setGeometry(QtCore.QRect(1330, 290, 121, 20))
        self.attack3RadioButton.setObjectName(_fromUtf8("attack3RadioButton"))
        self.saveInputPlotButton = QtGui.QPushButton(self.centralWidget)
        self.saveInputPlotButton.setEnabled(False)
        self.saveInputPlotButton.setGeometry(QtCore.QRect(520, 10, 31, 21))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/folder_image.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveInputPlotButton.setIcon(icon)
        self.saveInputPlotButton.setObjectName(_fromUtf8("saveInputPlotButton"))
        self.saveOutputPlotButton = QtGui.QPushButton(self.centralWidget)
        self.saveOutputPlotButton.setEnabled(False)
        self.saveOutputPlotButton.setGeometry(QtCore.QRect(530, 250, 31, 21))
        self.saveOutputPlotButton.setIcon(icon)
        self.saveOutputPlotButton.setObjectName(_fromUtf8("saveOutputPlotButton"))
        self.saveRightPlotButton = QtGui.QPushButton(self.centralWidget)
        self.saveRightPlotButton.setEnabled(False)
        self.saveRightPlotButton.setGeometry(QtCore.QRect(890, 10, 31, 21))
        self.saveRightPlotButton.setIcon(icon)
        self.saveRightPlotButton.setObjectName(_fromUtf8("saveRightPlotButton"))
        self.line = QtGui.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(260, 10, 20, 471))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.centralWidget)
        self.line_2.setGeometry(QtCore.QRect(450, 10, 20, 471))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.setKPButton = QtGui.QPushButton(self.centralWidget)
        self.setKPButton.setEnabled(False)
        self.setKPButton.setGeometry(QtCore.QRect(400, 120, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.setKPButton.setFont(font)
        self.setKPButton.setObjectName(_fromUtf8("setKPButton"))
        self.kpLabel = QtGui.QLabel(self.centralWidget)
        self.kpLabel.setEnabled(False)
        self.kpLabel.setGeometry(QtCore.QRect(270, 120, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.kpLabel.setFont(font)
        self.kpLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.kpLabel.setObjectName(_fromUtf8("kpLabel"))
        self.kpEdit = QtGui.QLineEdit(self.centralWidget)
        self.kpEdit.setEnabled(False)
        self.kpEdit.setGeometry(QtCore.QRect(330, 120, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.kpEdit.setFont(font)
        self.kpEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.kpEdit.setObjectName(_fromUtf8("kpEdit"))
        self.setKIButton = QtGui.QPushButton(self.centralWidget)
        self.setKIButton.setEnabled(False)
        self.setKIButton.setGeometry(QtCore.QRect(400, 150, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.setKIButton.setFont(font)
        self.setKIButton.setObjectName(_fromUtf8("setKIButton"))
        self.kiLabel = QtGui.QLabel(self.centralWidget)
        self.kiLabel.setEnabled(False)
        self.kiLabel.setGeometry(QtCore.QRect(270, 150, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.kiLabel.setFont(font)
        self.kiLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.kiLabel.setObjectName(_fromUtf8("kiLabel"))
        self.kiEdit = QtGui.QLineEdit(self.centralWidget)
        self.kiEdit.setEnabled(False)
        self.kiEdit.setGeometry(QtCore.QRect(330, 150, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.kiEdit.setFont(font)
        self.kiEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.kiEdit.setObjectName(_fromUtf8("kiEdit"))
        self.setTrimLeftButton = QtGui.QPushButton(self.centralWidget)
        self.setTrimLeftButton.setEnabled(False)
        self.setTrimLeftButton.setGeometry(QtCore.QRect(280, 200, 61, 51))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/arrow_left_12x12.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setTrimLeftButton.setIcon(icon1)
        self.setTrimLeftButton.setObjectName(_fromUtf8("setTrimLeftButton"))
        self.setTrimRightButton = QtGui.QPushButton(self.centralWidget)
        self.setTrimRightButton.setEnabled(False)
        self.setTrimRightButton.setGeometry(QtCore.QRect(390, 200, 61, 51))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/arrow_right_12x12.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setTrimRightButton.setIcon(icon2)
        self.setTrimRightButton.setObjectName(_fromUtf8("setTrimRightButton"))
        self.trimLabel = QtGui.QLabel(self.centralWidget)
        self.trimLabel.setEnabled(False)
        self.trimLabel.setGeometry(QtCore.QRect(340, 200, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.trimLabel.setFont(font)
        self.trimLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.trimLabel.setObjectName(_fromUtf8("trimLabel"))
        self.trimValueLabel = QtGui.QLabel(self.centralWidget)
        self.trimValueLabel.setEnabled(False)
        self.trimValueLabel.setGeometry(QtCore.QRect(340, 220, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.trimValueLabel.setFont(font)
        self.trimValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.trimValueLabel.setObjectName(_fromUtf8("trimValueLabel"))
        self.setAutotrimButton = QtGui.QPushButton(self.centralWidget)
        self.setAutotrimButton.setEnabled(False)
        self.setAutotrimButton.setGeometry(QtCore.QRect(1460, 200, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.setAutotrimButton.setFont(font)
        self.setAutotrimButton.setObjectName(_fromUtf8("setAutotrimButton"))
        self.autotrimLabel = QtGui.QLabel(self.centralWidget)
        self.autotrimLabel.setEnabled(False)
        self.autotrimLabel.setGeometry(QtCore.QRect(1330, 200, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.autotrimLabel.setFont(font)
        self.autotrimLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.autotrimLabel.setObjectName(_fromUtf8("autotrimLabel"))
        self.autotrimEdit = QtGui.QLineEdit(self.centralWidget)
        self.autotrimEdit.setEnabled(False)
        self.autotrimEdit.setGeometry(QtCore.QRect(1400, 200, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.autotrimEdit.setFont(font)
        self.autotrimEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.autotrimEdit.setObjectName(_fromUtf8("autotrimEdit"))
        self.frame = QtGui.QFrame(self.centralWidget)
        self.frame.setGeometry(QtCore.QRect(580, 250, 21, 21))
        self.frame.setStyleSheet(_fromUtf8("background-color: blue;"))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.frame_2 = QtGui.QFrame(self.centralWidget)
        self.frame_2.setGeometry(QtCore.QRect(650, 250, 21, 21))
        self.frame_2.setStyleSheet(_fromUtf8("background-color: green;"))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(610, 250, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(680, 250, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(750, 250, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.frame_3 = QtGui.QFrame(self.centralWidget)
        self.frame_3.setGeometry(QtCore.QRect(720, 250, 21, 21))
        self.frame_3.setStyleSheet(_fromUtf8("background-color: magenta;"))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.frame_4 = QtGui.QFrame(self.centralWidget)
        self.frame_4.setGeometry(QtCore.QRect(660, 10, 21, 21))
        self.frame_4.setStyleSheet(_fromUtf8("background-color: cyan;"))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.label_4 = QtGui.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(690, 10, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.frame_5 = QtGui.QFrame(self.centralWidget)
        self.frame_5.setGeometry(QtCore.QRect(570, 10, 21, 21))
        self.frame_5.setStyleSheet(_fromUtf8("background-color: red;"))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.label_5 = QtGui.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(600, 10, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.frame_6 = QtGui.QFrame(self.centralWidget)
        self.frame_6.setGeometry(QtCore.QRect(1050, 10, 21, 21))
        self.frame_6.setStyleSheet(_fromUtf8("background-color: cyan;"))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.label_6 = QtGui.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(1080, 10, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.frame_7 = QtGui.QFrame(self.centralWidget)
        self.frame_7.setGeometry(QtCore.QRect(940, 10, 21, 21))
        self.frame_7.setStyleSheet(_fromUtf8("background-color: blue;"))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.label_7 = QtGui.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(970, 10, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.saveButton = QtGui.QPushButton(self.centralWidget)
        self.saveButton.setEnabled(False)
        self.saveButton.setGeometry(QtCore.QRect(20, 440, 114, 41))
        self.saveButton.setStyleSheet(_fromUtf8("QPushButton:checked {background: rgba(60, 179, 113, 255);}"))
        self.saveButton.setCheckable(True)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1249, 22))
        self.menuBar.setNativeMenuBar(False)
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setMenuRole(QtGui.QAction.QuitRole)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setMenuRole(QtGui.QAction.AboutRole)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.landsharkButton, self.ccButton)
        MainWindow.setTabOrder(self.ccButton, self.rcButton)
        MainWindow.setTabOrder(self.rcButton, self.attackButton)
        MainWindow.setTabOrder(self.attackButton, self.desiredSpeedEdit)
        MainWindow.setTabOrder(self.desiredSpeedEdit, self.setSpeedButton)
        MainWindow.setTabOrder(self.setSpeedButton, self.console)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "HACMS Demo", None))
        self.landsharkButton.setText(_translate("MainWindow", "Landshark", None))
        self.rcButton.setText(_translate("MainWindow", "Resilient Controller", None))
        self.attackButton.setText(_translate("MainWindow", "Attack", None))
        self.estimatedLabel.setText(_translate("MainWindow", "Estimated", None))
        self.actualLabel.setText(_translate("MainWindow", "Actual", None))
        self.desiredSpeedLabel.setText(_translate("MainWindow", "Set Speed", None))
        self.desiredSpeedEdit.setText(_translate("MainWindow", "0.8", None))
        self.actualSpeedLabel.setText(_translate("MainWindow", "Actual Speed", None))
        self.outputPlotLabel.setText(_translate("MainWindow", "Output", None))
        self.estimatedSpeedLabel.setText(_translate("MainWindow", "Estimated Speed", None))
        self.ccButton.setText(_translate("MainWindow", "Cruise Control", None))
        self.setSpeedButton.setText(_translate("MainWindow", "Set", None))
        self.inputPlotLabel.setText(_translate("MainWindow", "Input", None))
        self.rightPlotLabel.setText(_translate("MainWindow", "Odometry", None))
        self.attack1RadioButton.setText(_translate("MainWindow", "Attack Mode 1", None))
        self.attack2RadioButton.setText(_translate("MainWindow", "Attack Mode 2", None))
        self.attack3RadioButton.setText(_translate("MainWindow", "Attack Mode 3", None))
        self.setKPButton.setText(_translate("MainWindow", "Set", None))
        self.kpLabel.setText(_translate("MainWindow", "KP", None))
        self.kpEdit.setText(_translate("MainWindow", "0.05", None))
        self.setKIButton.setText(_translate("MainWindow", "Set", None))
        self.kiLabel.setText(_translate("MainWindow", "KI", None))
        self.kiEdit.setText(_translate("MainWindow", "0.2", None))
        self.trimLabel.setText(_translate("MainWindow", "Trim", None))
        self.trimValueLabel.setText(_translate("MainWindow", "0.0", None))
        self.setAutotrimButton.setText(_translate("MainWindow", "Set", None))
        self.autotrimLabel.setText(_translate("MainWindow", "Autotrim", None))
        self.autotrimEdit.setText(_translate("MainWindow", "0.001", None))
        self.label.setText(_translate("MainWindow", "LE", None))
        self.label_2.setText(_translate("MainWindow", "RE", None))
        self.label_3.setText(_translate("MainWindow", "GPS", None))
        self.label_4.setText(_translate("MainWindow", "REF", None))
        self.label_5.setText(_translate("MainWindow", "CMD", None))
        self.label_6.setText(_translate("MainWindow", "REF", None))
        self.label_7.setText(_translate("MainWindow", "SPEED", None))
        self.saveButton.setText(_translate("MainWindow", "Save", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))

import images_rc
