# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created: Thu Dec 19 14:37:56 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1275, 693)
        MainWindow.setMinimumSize(QtCore.QSize(1275, 693))
        MainWindow.setMaximumSize(QtCore.QSize(1275, 693))
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.landsharkButton = QtGui.QPushButton(self.centralWidget)
        self.landsharkButton.setGeometry(QtCore.QRect(10, 20, 241, 91))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.landsharkButton.setFont(font)
        self.landsharkButton.setStyleSheet(_fromUtf8("QPushButton:checked {background: rgba(60, 179, 113, 255);}"))
        self.landsharkButton.setCheckable(True)
        self.landsharkButton.setObjectName(_fromUtf8("landsharkButton"))
        self.rcButton = QtGui.QPushButton(self.centralWidget)
        self.rcButton.setEnabled(False)
        self.rcButton.setGeometry(QtCore.QRect(10, 280, 241, 91))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.rcButton.setFont(font)
        self.rcButton.setStyleSheet(_fromUtf8("QPushButton:checked {background: rgba(60, 179, 113, 255);}"))
        self.rcButton.setCheckable(True)
        self.rcButton.setObjectName(_fromUtf8("rcButton"))
        self.attackButton = QtGui.QPushButton(self.centralWidget)
        self.attackButton.setEnabled(False)
        self.attackButton.setGeometry(QtCore.QRect(10, 380, 111, 151))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.attackButton.setFont(font)
        self.attackButton.setStyleSheet(_fromUtf8("QPushButton:checked {background: red;}"))
        self.attackButton.setCheckable(True)
        self.attackButton.setObjectName(_fromUtf8("attackButton"))
        self.console = QtGui.QPlainTextEdit(self.centralWidget)
        self.console.setGeometry(QtCore.QRect(10, 540, 1251, 101))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(13)
        self.console.setFont(font)
        self.console.setPlainText(_fromUtf8(""))
        self.console.setObjectName(_fromUtf8("console"))
        self.ccButton = QtGui.QPushButton(self.centralWidget)
        self.ccButton.setEnabled(False)
        self.ccButton.setGeometry(QtCore.QRect(10, 120, 241, 91))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.ccButton.setFont(font)
        self.ccButton.setStyleSheet(_fromUtf8("QPushButton:checked {background: rgba(60, 179, 113, 255);}"))
        self.ccButton.setCheckable(True)
        self.ccButton.setObjectName(_fromUtf8("ccButton"))
        self.saveButton = QtGui.QPushButton(self.centralWidget)
        self.saveButton.setEnabled(False)
        self.saveButton.setGeometry(QtCore.QRect(10, 220, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.saveButton.setFont(font)
        self.saveButton.setStyleSheet(_fromUtf8("QPushButton:checked {background: rgba(60, 179, 113, 255);}"))
        self.saveButton.setCheckable(True)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setEnabled(False)
        self.tabWidget.setGeometry(QtCore.QRect(270, 10, 991, 521))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.control_tab = QtGui.QWidget()
        self.control_tab.setObjectName(_fromUtf8("control_tab"))
        self.actualSpeedLCD = QtGui.QLCDNumber(self.control_tab)
        self.actualSpeedLCD.setEnabled(False)
        self.actualSpeedLCD.setGeometry(QtCore.QRect(10, 300, 171, 71))
        self.actualSpeedLCD.setObjectName(_fromUtf8("actualSpeedLCD"))
        self.trimLabel = QtGui.QLabel(self.control_tab)
        self.trimLabel.setEnabled(False)
        self.trimLabel.setGeometry(QtCore.QRect(70, 210, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.trimLabel.setFont(font)
        self.trimLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.trimLabel.setObjectName(_fromUtf8("trimLabel"))
        self.outputPlotLabel = QtGui.QLabel(self.control_tab)
        self.outputPlotLabel.setEnabled(False)
        self.outputPlotLabel.setGeometry(QtCore.QRect(200, 250, 51, 16))
        self.outputPlotLabel.setObjectName(_fromUtf8("outputPlotLabel"))
        self.cmdLabelColor = QtGui.QFrame(self.control_tab)
        self.cmdLabelColor.setGeometry(QtCore.QRect(250, 10, 21, 21))
        self.cmdLabelColor.setStyleSheet(_fromUtf8("background-color: red;"))
        self.cmdLabelColor.setFrameShape(QtGui.QFrame.StyledPanel)
        self.cmdLabelColor.setFrameShadow(QtGui.QFrame.Raised)
        self.cmdLabelColor.setObjectName(_fromUtf8("cmdLabelColor"))
        self.setTrimLeftButton = QtGui.QPushButton(self.control_tab)
        self.setTrimLeftButton.setEnabled(False)
        self.setTrimLeftButton.setGeometry(QtCore.QRect(10, 210, 61, 51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/arrow_left_12x12.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setTrimLeftButton.setIcon(icon)
        self.setTrimLeftButton.setObjectName(_fromUtf8("setTrimLeftButton"))
        self.gpsLabel = QtGui.QLabel(self.control_tab)
        self.gpsLabel.setGeometry(QtCore.QRect(290, 250, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.gpsLabel.setFont(font)
        self.gpsLabel.setObjectName(_fromUtf8("gpsLabel"))
        self.kiLabel = QtGui.QLabel(self.control_tab)
        self.kiLabel.setEnabled(False)
        self.kiLabel.setGeometry(QtCore.QRect(0, 150, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.kiLabel.setFont(font)
        self.kiLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.kiLabel.setObjectName(_fromUtf8("kiLabel"))
        self.actualSpeedLabel = QtGui.QLabel(self.control_tab)
        self.actualSpeedLabel.setEnabled(False)
        self.actualSpeedLabel.setGeometry(QtCore.QRect(0, 280, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.actualSpeedLabel.setFont(font)
        self.actualSpeedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.actualSpeedLabel.setObjectName(_fromUtf8("actualSpeedLabel"))
        self.estimatedSpeedLCD = QtGui.QLCDNumber(self.control_tab)
        self.estimatedSpeedLCD.setEnabled(False)
        self.estimatedSpeedLCD.setGeometry(QtCore.QRect(10, 410, 171, 71))
        self.estimatedSpeedLCD.setObjectName(_fromUtf8("estimatedSpeedLCD"))
        self.setKIButton = QtGui.QPushButton(self.control_tab)
        self.setKIButton.setEnabled(False)
        self.setKIButton.setGeometry(QtCore.QRect(130, 150, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.setKIButton.setFont(font)
        self.setKIButton.setObjectName(_fromUtf8("setKIButton"))
        self.cmdLabel = QtGui.QLabel(self.control_tab)
        self.cmdLabel.setGeometry(QtCore.QRect(280, 10, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cmdLabel.setFont(font)
        self.cmdLabel.setObjectName(_fromUtf8("cmdLabel"))
        self.leLabel = QtGui.QLabel(self.control_tab)
        self.leLabel.setGeometry(QtCore.QRect(370, 250, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.leLabel.setFont(font)
        self.leLabel.setObjectName(_fromUtf8("leLabel"))
        self.refLabel2 = QtGui.QLabel(self.control_tab)
        self.refLabel2.setGeometry(QtCore.QRect(760, 10, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.refLabel2.setFont(font)
        self.refLabel2.setObjectName(_fromUtf8("refLabel2"))
        self.refLabelColor2 = QtGui.QFrame(self.control_tab)
        self.refLabelColor2.setGeometry(QtCore.QRect(730, 10, 21, 21))
        self.refLabelColor2.setStyleSheet(_fromUtf8("background-color: cyan;"))
        self.refLabelColor2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.refLabelColor2.setFrameShadow(QtGui.QFrame.Raised)
        self.refLabelColor2.setObjectName(_fromUtf8("refLabelColor2"))
        self.rightPlotLabel = QtGui.QLabel(self.control_tab)
        self.rightPlotLabel.setEnabled(False)
        self.rightPlotLabel.setGeometry(QtCore.QRect(540, 10, 71, 16))
        self.rightPlotLabel.setObjectName(_fromUtf8("rightPlotLabel"))
        self.desiredSpeedEdit = QtGui.QLineEdit(self.control_tab)
        self.desiredSpeedEdit.setEnabled(False)
        self.desiredSpeedEdit.setGeometry(QtCore.QRect(10, 50, 91, 39))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.desiredSpeedEdit.setFont(font)
        self.desiredSpeedEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.desiredSpeedEdit.setObjectName(_fromUtf8("desiredSpeedEdit"))
        self.desiredSpeedLabel = QtGui.QLabel(self.control_tab)
        self.desiredSpeedLabel.setEnabled(False)
        self.desiredSpeedLabel.setGeometry(QtCore.QRect(10, 9, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.desiredSpeedLabel.setFont(font)
        self.desiredSpeedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.desiredSpeedLabel.setObjectName(_fromUtf8("desiredSpeedLabel"))
        self.setSpeedButton = QtGui.QPushButton(self.control_tab)
        self.setSpeedButton.setEnabled(False)
        self.setSpeedButton.setGeometry(QtCore.QRect(110, 50, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.setSpeedButton.setFont(font)
        self.setSpeedButton.setObjectName(_fromUtf8("setSpeedButton"))
        self.line_2 = QtGui.QFrame(self.control_tab)
        self.line_2.setGeometry(QtCore.QRect(180, 10, 20, 471))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.kpEdit = QtGui.QLineEdit(self.control_tab)
        self.kpEdit.setEnabled(False)
        self.kpEdit.setGeometry(QtCore.QRect(60, 120, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.kpEdit.setFont(font)
        self.kpEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.kpEdit.setObjectName(_fromUtf8("kpEdit"))
        self.speedLabel = QtGui.QLabel(self.control_tab)
        self.speedLabel.setGeometry(QtCore.QRect(650, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.speedLabel.setFont(font)
        self.speedLabel.setObjectName(_fromUtf8("speedLabel"))
        self.trimValueLabel = QtGui.QLabel(self.control_tab)
        self.trimValueLabel.setEnabled(False)
        self.trimValueLabel.setGeometry(QtCore.QRect(70, 230, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.trimValueLabel.setFont(font)
        self.trimValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.trimValueLabel.setObjectName(_fromUtf8("trimValueLabel"))
        self.kiEdit = QtGui.QLineEdit(self.control_tab)
        self.kiEdit.setEnabled(False)
        self.kiEdit.setGeometry(QtCore.QRect(60, 150, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.kiEdit.setFont(font)
        self.kiEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.kiEdit.setObjectName(_fromUtf8("kiEdit"))
        self.estimatedSpeedLabel = QtGui.QLabel(self.control_tab)
        self.estimatedSpeedLabel.setEnabled(False)
        self.estimatedSpeedLabel.setGeometry(QtCore.QRect(0, 390, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.estimatedSpeedLabel.setFont(font)
        self.estimatedSpeedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.estimatedSpeedLabel.setObjectName(_fromUtf8("estimatedSpeedLabel"))
        self.inputPlotLabel = QtGui.QLabel(self.control_tab)
        self.inputPlotLabel.setEnabled(False)
        self.inputPlotLabel.setGeometry(QtCore.QRect(200, 10, 41, 16))
        self.inputPlotLabel.setObjectName(_fromUtf8("inputPlotLabel"))
        self.speedLabelColor = QtGui.QFrame(self.control_tab)
        self.speedLabelColor.setGeometry(QtCore.QRect(620, 10, 21, 21))
        self.speedLabelColor.setStyleSheet(_fromUtf8("background-color: blue;"))
        self.speedLabelColor.setFrameShape(QtGui.QFrame.StyledPanel)
        self.speedLabelColor.setFrameShadow(QtGui.QFrame.Raised)
        self.speedLabelColor.setObjectName(_fromUtf8("speedLabelColor"))
        self.refLabel = QtGui.QLabel(self.control_tab)
        self.refLabel.setGeometry(QtCore.QRect(370, 10, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.refLabel.setFont(font)
        self.refLabel.setObjectName(_fromUtf8("refLabel"))
        self.setKPButton = QtGui.QPushButton(self.control_tab)
        self.setKPButton.setEnabled(False)
        self.setKPButton.setGeometry(QtCore.QRect(130, 120, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.setKPButton.setFont(font)
        self.setKPButton.setObjectName(_fromUtf8("setKPButton"))
        self.reLabel = QtGui.QLabel(self.control_tab)
        self.reLabel.setGeometry(QtCore.QRect(440, 250, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reLabel.setFont(font)
        self.reLabel.setObjectName(_fromUtf8("reLabel"))
        self.refLabelColor = QtGui.QFrame(self.control_tab)
        self.refLabelColor.setGeometry(QtCore.QRect(340, 10, 21, 21))
        self.refLabelColor.setStyleSheet(_fromUtf8("background-color: cyan;"))
        self.refLabelColor.setFrameShape(QtGui.QFrame.StyledPanel)
        self.refLabelColor.setFrameShadow(QtGui.QFrame.Raised)
        self.refLabelColor.setObjectName(_fromUtf8("refLabelColor"))
        self.setTrimRightButton = QtGui.QPushButton(self.control_tab)
        self.setTrimRightButton.setEnabled(False)
        self.setTrimRightButton.setGeometry(QtCore.QRect(120, 210, 61, 51))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/arrow_right_12x12.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setTrimRightButton.setIcon(icon1)
        self.setTrimRightButton.setObjectName(_fromUtf8("setTrimRightButton"))
        self.kpLabel = QtGui.QLabel(self.control_tab)
        self.kpLabel.setEnabled(False)
        self.kpLabel.setGeometry(QtCore.QRect(0, 120, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.kpLabel.setFont(font)
        self.kpLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.kpLabel.setObjectName(_fromUtf8("kpLabel"))
        self.reLabelColor = QtGui.QFrame(self.control_tab)
        self.reLabelColor.setGeometry(QtCore.QRect(410, 250, 21, 21))
        self.reLabelColor.setStyleSheet(_fromUtf8("background-color: green;"))
        self.reLabelColor.setFrameShape(QtGui.QFrame.StyledPanel)
        self.reLabelColor.setFrameShadow(QtGui.QFrame.Raised)
        self.reLabelColor.setObjectName(_fromUtf8("reLabelColor"))
        self.leLabelColor = QtGui.QFrame(self.control_tab)
        self.leLabelColor.setGeometry(QtCore.QRect(340, 250, 21, 21))
        self.leLabelColor.setStyleSheet(_fromUtf8("background-color: blue;"))
        self.leLabelColor.setFrameShape(QtGui.QFrame.StyledPanel)
        self.leLabelColor.setFrameShadow(QtGui.QFrame.Raised)
        self.leLabelColor.setObjectName(_fromUtf8("leLabelColor"))
        self.gpsLabelColor = QtGui.QFrame(self.control_tab)
        self.gpsLabelColor.setGeometry(QtCore.QRect(260, 250, 21, 21))
        self.gpsLabelColor.setStyleSheet(_fromUtf8("background-color: magenta;"))
        self.gpsLabelColor.setFrameShape(QtGui.QFrame.StyledPanel)
        self.gpsLabelColor.setFrameShadow(QtGui.QFrame.Raised)
        self.gpsLabelColor.setObjectName(_fromUtf8("gpsLabelColor"))
        self.rightPlot = PlotWidget(self.control_tab)
        self.rightPlot.setGeometry(QtCore.QRect(540, 40, 431, 441))
        self.rightPlot.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rightPlot.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rightPlot.setObjectName(_fromUtf8("rightPlot"))
        self.inputPlot = PlotWidget(self.control_tab)
        self.inputPlot.setGeometry(QtCore.QRect(200, 40, 331, 201))
        self.inputPlot.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.inputPlot.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.inputPlot.setObjectName(_fromUtf8("inputPlot"))
        self.outputPlot = PlotWidget(self.control_tab)
        self.outputPlot.setGeometry(QtCore.QRect(200, 280, 331, 201))
        self.outputPlot.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.outputPlot.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.outputPlot.setObjectName(_fromUtf8("outputPlot"))
        self.tabWidget.addTab(self.control_tab, _fromUtf8(""))
        self.nav_tab = QtGui.QWidget()
        self.nav_tab.setObjectName(_fromUtf8("nav_tab"))
        self.waypointListView = QtGui.QListView(self.nav_tab)
        self.waypointListView.setEnabled(False)
        self.waypointListView.setGeometry(QtCore.QRect(10, 41, 201, 401))
        self.waypointListView.setObjectName(_fromUtf8("waypointListView"))
        self.waypointLabel = QtGui.QLabel(self.nav_tab)
        self.waypointLabel.setEnabled(False)
        self.waypointLabel.setGeometry(QtCore.QRect(10, 0, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.waypointLabel.setFont(font)
        self.waypointLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.waypointLabel.setObjectName(_fromUtf8("waypointLabel"))
        self.addWaypointButton = QtGui.QPushButton(self.nav_tab)
        self.addWaypointButton.setEnabled(False)
        self.addWaypointButton.setGeometry(QtCore.QRect(10, 450, 41, 32))
        self.addWaypointButton.setObjectName(_fromUtf8("addWaypointButton"))
        self.removeWaypointButton = QtGui.QPushButton(self.nav_tab)
        self.removeWaypointButton.setEnabled(False)
        self.removeWaypointButton.setGeometry(QtCore.QRect(60, 450, 41, 32))
        self.removeWaypointButton.setObjectName(_fromUtf8("removeWaypointButton"))
        self.uploadWaypointsButton = QtGui.QPushButton(self.nav_tab)
        self.uploadWaypointsButton.setEnabled(False)
        self.uploadWaypointsButton.setGeometry(QtCore.QRect(160, 450, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uploadWaypointsButton.setFont(font)
        self.uploadWaypointsButton.setObjectName(_fromUtf8("uploadWaypointsButton"))
        self.navView = QtGui.QGraphicsView(self.nav_tab)
        self.navView.setGeometry(QtCore.QRect(230, 10, 741, 471))
        self.navView.setObjectName(_fromUtf8("navView"))
        self.clearWaypointsButton = QtGui.QPushButton(self.nav_tab)
        self.clearWaypointsButton.setEnabled(False)
        self.clearWaypointsButton.setGeometry(QtCore.QRect(110, 450, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.clearWaypointsButton.setFont(font)
        self.clearWaypointsButton.setObjectName(_fromUtf8("clearWaypointsButton"))
        self.tabWidget.addTab(self.nav_tab, _fromUtf8(""))
        self.enclCheckBox = QtGui.QCheckBox(self.centralWidget)
        self.enclCheckBox.setEnabled(False)
        self.enclCheckBox.setGeometry(QtCore.QRect(130, 459, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.enclCheckBox.setFont(font)
        self.enclCheckBox.setObjectName(_fromUtf8("enclCheckBox"))
        self.attackComboBox = QtGui.QComboBox(self.centralWidget)
        self.attackComboBox.setEnabled(False)
        self.attackComboBox.setGeometry(QtCore.QRect(130, 390, 121, 26))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.attackComboBox.setFont(font)
        self.attackComboBox.setObjectName(_fromUtf8("attackComboBox"))
        self.attackComboBox.addItem(_fromUtf8(""))
        self.attackComboBox.addItem(_fromUtf8(""))
        self.attackComboBox.addItem(_fromUtf8(""))
        self.encrCheckBox = QtGui.QCheckBox(self.centralWidget)
        self.encrCheckBox.setEnabled(False)
        self.encrCheckBox.setGeometry(QtCore.QRect(130, 489, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.encrCheckBox.setFont(font)
        self.encrCheckBox.setObjectName(_fromUtf8("encrCheckBox"))
        self.gpsCheckBox = QtGui.QCheckBox(self.centralWidget)
        self.gpsCheckBox.setEnabled(False)
        self.gpsCheckBox.setGeometry(QtCore.QRect(130, 429, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.gpsCheckBox.setFont(font)
        self.gpsCheckBox.setObjectName(_fromUtf8("gpsCheckBox"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1275, 22))
        self.menuBar.setNativeMenuBar(False)
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setMenuRole(QtGui.QAction.QuitRole)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setMenuRole(QtGui.QAction.AboutRole)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.landsharkButton, self.ccButton)
        MainWindow.setTabOrder(self.ccButton, self.saveButton)
        MainWindow.setTabOrder(self.saveButton, self.rcButton)
        MainWindow.setTabOrder(self.rcButton, self.attackButton)
        MainWindow.setTabOrder(self.attackButton, self.desiredSpeedEdit)
        MainWindow.setTabOrder(self.desiredSpeedEdit, self.setSpeedButton)
        MainWindow.setTabOrder(self.setSpeedButton, self.kpEdit)
        MainWindow.setTabOrder(self.kpEdit, self.setKPButton)
        MainWindow.setTabOrder(self.setKPButton, self.kiEdit)
        MainWindow.setTabOrder(self.kiEdit, self.setKIButton)
        MainWindow.setTabOrder(self.setKIButton, self.setTrimLeftButton)
        MainWindow.setTabOrder(self.setTrimLeftButton, self.setTrimRightButton)
        MainWindow.setTabOrder(self.setTrimRightButton, self.console)
        MainWindow.setTabOrder(self.console, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.waypointListView)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "HACMS Demo", None))
        self.landsharkButton.setText(_translate("MainWindow", "Landshark", None))
        self.rcButton.setText(_translate("MainWindow", "Resilient\n"
"Controller", None))
        self.attackButton.setText(_translate("MainWindow", "Attack", None))
        self.ccButton.setText(_translate("MainWindow", "Cruise Control", None))
        self.saveButton.setText(_translate("MainWindow", "Save Data", None))
        self.trimLabel.setText(_translate("MainWindow", "Trim", None))
        self.outputPlotLabel.setText(_translate("MainWindow", "Output", None))
        self.gpsLabel.setText(_translate("MainWindow", "GPS", None))
        self.kiLabel.setText(_translate("MainWindow", "KI", None))
        self.actualSpeedLabel.setText(_translate("MainWindow", "Actual Speed", None))
        self.setKIButton.setText(_translate("MainWindow", "Set", None))
        self.cmdLabel.setText(_translate("MainWindow", "CMD", None))
        self.leLabel.setText(_translate("MainWindow", "LE", None))
        self.refLabel2.setText(_translate("MainWindow", "REF", None))
        self.rightPlotLabel.setText(_translate("MainWindow", "Odometry", None))
        self.desiredSpeedEdit.setText(_translate("MainWindow", "0.8", None))
        self.desiredSpeedLabel.setText(_translate("MainWindow", "Set Speed", None))
        self.setSpeedButton.setText(_translate("MainWindow", "Set", None))
        self.kpEdit.setText(_translate("MainWindow", "0.05", None))
        self.speedLabel.setText(_translate("MainWindow", "SPEED", None))
        self.trimValueLabel.setText(_translate("MainWindow", "0.0", None))
        self.kiEdit.setText(_translate("MainWindow", "0.2", None))
        self.estimatedSpeedLabel.setText(_translate("MainWindow", "Estimated Speed", None))
        self.inputPlotLabel.setText(_translate("MainWindow", "Input", None))
        self.refLabel.setText(_translate("MainWindow", "REF", None))
        self.setKPButton.setText(_translate("MainWindow", "Set", None))
        self.reLabel.setText(_translate("MainWindow", "RE", None))
        self.kpLabel.setText(_translate("MainWindow", "KP", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.control_tab), _translate("MainWindow", "Control", None))
        self.waypointLabel.setText(_translate("MainWindow", "Waypoints", None))
        self.addWaypointButton.setText(_translate("MainWindow", "+", None))
        self.removeWaypointButton.setText(_translate("MainWindow", "-", None))
        self.uploadWaypointsButton.setText(_translate("MainWindow", "Upload", None))
        self.clearWaypointsButton.setText(_translate("MainWindow", "Clear", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.nav_tab), _translate("MainWindow", "Navigation", None))
        self.enclCheckBox.setText(_translate("MainWindow", "ENC LEFT", None))
        self.attackComboBox.setItemText(0, _translate("MainWindow", "Constant", None))
        self.attackComboBox.setItemText(1, _translate("MainWindow", "Random", None))
        self.attackComboBox.setItemText(2, _translate("MainWindow", "Alternating", None))
        self.encrCheckBox.setText(_translate("MainWindow", "ENC RIGHT", None))
        self.gpsCheckBox.setText(_translate("MainWindow", "GPS", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))

from pyqtgraph import PlotWidget
import images_rc
